name: mqpilot
version: '3.8'
services:
  edge_sensor:
    build: ./edge_sensor
    container_name: edge_sensor
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - iot_lan
    volumes:
      - ./edge_sensor:/edge_sensor
      - ./Data/PCAP:/pcaps

  iot_broker:
    image: eclipse-mosquitto:latest
    container_name: iot_broker
    ports:
      - "1883:1883"
    networks:
      - iot_lan
    volumes:
      - ./iot_broker/mosquitto.conf:/mosquitto/config/mosquitto.conf

  cloud_tier:
    image: python:3.11-slim
    container_name: cloud_tier
    ports:
      - "5000:5000"
    networks:
      - iot_lan
    volumes:
      - ./cloud_tier/api:/cloud_tier/api
      - ./edge_sensor/logs:/edge_sensor/logs
    working_dir: /cloud_tier/api
    command: /bin/bash -c "pip install flask && python -m flask run --host=0.0.0.0"

  attacker_kali:
    image: kalilinux/kali-rolling
    container_name: attacker_kali
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - iot_lan
    command: /bin/bash -c "apt update && apt install -y hydra mosquitto-clients && tail -f /dev/null"

networks:
  iot_lan:
    driver: bridge
